# ----------------------
# 1. Convertion stage
# ----------------------
FROM php:8.4-cli AS converter

# TODO: adjust accordingly
RUN php -v

# ----------------------
# 2. Build stage
# ----------------------
FROM node:22-alpine AS builder

# Install git (needed by VitePress for lastUpdated, etc.)
RUN apk add --no-cache git

# Copy source
WORKDIR /app
COPY . .

# TODO: Copy built files
#COPY --from=converter /tmp /app/vitepress/markdown/en

# Install vitepress deps
WORKDIR /app/vitepress
RUN npm ci

# Build VitePress site
RUN npm run docs:build

# ----------------------
# 3. Runtime stage (nginx)
# ----------------------
FROM nginx:1.27-alpine AS runner

# Copy built files
COPY --from=builder /app/.vitepress/dist /usr/share/nginx/html

# Expose port
EXPOSE 80

# Health check (optional)
HEALTHCHECK CMD wget --quiet --tries=1 --spider http://localhost:80/ || exit 1

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
